version: "3.4"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    command: --no-auth
    ports:
      - "9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.middlewares=auth"

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIGROOT}/traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-rtr.entrypoints=websecure"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-rtr.tls=true"
      - "traefik.http.routers.traefik-rtr.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      - "traefik.http.routers.traefik-rtr.middlewares=auth"
      - "traefik.http.services.traefik-rtr.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.auth.forwardauth.address=https://${DOMAIN}/api/v2/auth?group=1"

  openldap:
    container_name: openldap
    image: osixia/openldap:1.4.0
    tty: true
    stdin_open: true
    ports:
      - 389:389
      - 636:636
    volumes:
      - ${CONFIGROOT}/openldap/db:/var/lib/ldap
      - ${CONFIGROOT}/openldap/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=readonly
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
      - LDAP_TLS=false

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    depends_on:
      - openldap
    ports:
      - 8083:80
    volumes:
      - ${CONFIGROOT}/openldap/db:/var/lib/ldap
      - ${CONFIGROOT}/openldap/config:/etc/ldap/slapd.d
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ${CONFIGROOT}/organizr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TZ}
      - fpm=true
      - branch=v2-develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.organizr.entrypoints=websecure"
      - "traefik.http.routers.organizr.tls.certresolver=myresolver"

  qbittorrentvpn:
    container_name: qbittorrentvpn
    image: binhex/arch-qbittorrentvpn:latest
    depends_on:
      - traefik
    restart: always
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - VPN_PROV=custom
      - VPN_CLIENT=wireguard
      - LAN_NETWORK=${LAN_NETWORK}
      - WEBUI_PORT=8112
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8112:8112
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MEDIAROOT}/downloads:/media/downloads
      - ${CONFIGROOT}/qbittorrentvpn:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8112"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=myresolver"
      - "traefik.http.routers.qbittorrent.rule=Host(`torrent.${DOMAIN}`)"

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    depends_on:
      - traefik
      - organizr
    restart: always
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${MEDIAROOT}/downloads/torrent-blackhole:/media/downloads
      - ${CONFIGROOT}/jackett:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN}`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
      - "traefik.http.routers.jackett.middlewares=auth"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    depends_on:
      - traefik
      - organizr
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${CONFIGROOT}/sonarr:/config
      - ${MEDIAROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN}`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr.middlewares=auth"
      - "traefik.http.routers.sonarr.priority=1"
      - "traefik.http.routers.sonarr-api.rule=Host(`sonarr.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.sonarr-api.entrypoints=websecure"
      - "traefik.http.routers.sonarr-api.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr-api.priority=2"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:nightly
    depends_on:
      - traefik
      - organizr
    restart: always
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${CONFIGROOT}/radarr:/config
      - ${MEDIAROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr.middlewares=auth"
      - "traefik.http.routers.radarr.priority=1"
      - "traefik.http.routers.radarr-api.rule=Host(`radarr.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.radarr-api.entrypoints=websecure"
      - "traefik.http.routers.radarr-api.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr-api.priority=2"

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    depends_on:
      - postgres
      - redis
    user: ${PUID}:${PGID}
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASS}
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=nc.${DOMAIN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/nextcloud:/var/www/html
      - ${MEDIAROOT}/nextcloud:/var/www/html/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nc.${DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.middlewares=cloud_headers,cloud_redirectregex"
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://${DOMAIN}"
      - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAIN}"
      - "traefik.http.middlewares.cloud_headers.headers.framedeny=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsPreload=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsSeconds=15552001"
      - "traefik.http.middlewares.cloud_redirectregex.redirectregex.regex=/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.cloud_redirectregex.redirectregex.replacement=/remote.php/dav/"

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin:latest
    depends_on:
      - traefik
      - organizr
    restart: always
    ports:
      - 8096:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${CONFIGROOT}/jellyfin:/config
      - ${MEDIAROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`) || (Host(`${DOMAIN}`) && PathPrefix(`/jellyfin`))"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"

  pp-1:
    container_name: pp-1
    image: photoprism/photoprism:latest
    restart: always
    user: "${PUID}:${PGID}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "photoprism", "status"]
      interval: 60s
      timeout: 15s
      retries: 5
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_PUBLIC=false
      - PHOTOPRISM_SITE_URL=https://pp-1.${DOMAIN}/
      - PHOTOPRISM_HTTP_PORT=2342
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_DSN=photoprism:${PHOTOPRISM_DATABASE_PASS}@tcp(mariadb:3306)/pp_1?charset=utf8mb4,utf8&parseTime=true
      - PHOTOPRISM_ORIGINALS_LIMIT=10000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/pp-1:/photoprism/storage
      - ${MEDIAROOT}/nextcloud/mesnigan/files/Photos:/photoprism/originals
      - ${MEDIAROOT}/nextcloud/mesnigan/files/Videos:/photoprism/originals/Videos
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pp-1.loadbalancer.server.port=2342"
      - "traefik.http.routers.pp-1.entrypoints=websecure"
      - "traefik.http.routers.pp-1.tls.certresolver=myresolver"
      - "traefik.http.routers.pp-1.rule=Host(`pp-1.${DOMAIN}`)"

  pp-2:
    container_name: pp-2
    image: photoprism/photoprism:latest
    restart: always
    user: "${PUID}:${PGID}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2343:2343
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "photoprism", "status"]
      interval: 60s
      timeout: 15s
      retries: 5
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${PHOTOPRISM_ADMIN_PASSWORD}
      - PHOTOPRISM_PUBLIC=false
      - PHOTOPRISM_SITE_URL=https://pp-2.${DOMAIN}/
      - PHOTOPRISM_HTTP_PORT=2343
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_DSN=photoprism:${PHOTOPRISM_DATABASE_PASS}@tcp(mariadb:3306)/pp_2?charset=utf8mb4,utf8&parseTime=true
      - PHOTOPRISM_ORIGINALS_LIMIT=10000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/pp-2:/photoprism/storage
      - ${MEDIAROOT}/photos/jimmy:/photoprism/originals
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.pp-2.loadbalancer.server.port=2343"
      - "traefik.http.routers.pp-2.entrypoints=websecure"
      - "traefik.http.routers.pp-2.tls.certresolver=myresolver"
      - "traefik.http.routers.pp-2.rule=Host(`pp-2.${DOMAIN}`)"

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb
    entrypoint: sh -c "
      echo 'CREATE USER IF NOT EXISTS \"photoprism\"@\"%\" IDENTIFIED BY \"${PHOTOPRISM_DATABASE_PASS}\";
      CREATE DATABASE IF NOT EXISTS pp_1;
      CREATE DATABASE IF NOT EXISTS pp_2;
      GRANT ALL PRIVILEGES ON *.* TO \"photoprism\"@\"%\";' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/db/mariadb:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DATABASE_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/db/postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIGROOT}/db/redis:/data
