version: "3.4"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}" 
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT}/config/traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) && (PathPrefix(`/traefik/`) || Headers(`Referer`, `https://${DOMAIN}/traefik/dashboard/`))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=traefik-strip-prefix"
      - "traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes=/traefik"
      - "traefik.http.middlewares.auth.forwardauth.address=http://organizr/api/v2/auth?group=1"

  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ${ROOT}/config/organizr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
      - TZ=${TZ}
      - fpm=true
      - branch=v2-develop
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.organizr.entrypoints=websecure"
      - "traefik.http.routers.organizr.tls.certresolver=myresolver"

  qbittorrentvpn:
    container_name: qbittorrentvpn
    image: binhex/arch-qbittorrentvpn:latest
    depends_on:
      - traefik
      - organizr
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - VPN_PROV=custom
      - VPN_CLIENT=wireguard
      - LAN_NETWORK=${LAN_NETWORK}
      - WEBUI_PORT=8112
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=022
    ports:
      - 8112:8112
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads:/media/downloads
      - ${ROOT}/config/qbittorrentvpn:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8112"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls.certresolver=myresolver"
      - "traefik.http.routers.qbittorrent.rule=Host(`${DOMAIN}`) && PathPrefix(`/qbittorrent/`)"
      - "traefik.http.routers.qbittorrent.middlewares=qbittorrent-stripprefix,auth"
      - "traefik.http.middlewares.qbittorrent-stripprefix.stripPrefix.prefixes=/qbittorrent"

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/downloads/torrent-blackhole:/media/downloads
      - ${ROOT}/config/jackett:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`${DOMAIN}`) && PathPrefix(`/jackett`)"
      - "traefik.http.routers.jackett.entrypoints=websecure"
      - "traefik.http.routers.jackett.tls.certresolver=myresolver"
      - "traefik.http.routers.jackett.middlewares=auth"

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:preview
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=myresolver"
      - "traefik.http.routers.sonarr.middlewares=auth"

  radarr:
    container_name: radarr
    image: linuxserver/radarr:nightly
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${ROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=myresolver"
      - "traefik.http.routers.radarr.middlewares=auth"

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr:nightly
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 8686:8686
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/lidarr:/config
      - ${ROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/lidarr`)"
      - "traefik.http.routers.lidarr.entrypoints=websecure"
      - "traefik.http.routers.lidarr.tls.certresolver=myresolver"
      - "traefik.http.routers.lidarr.middlewares=auth"

  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin:latest
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/jellyfin:/config
      - ${ROOT}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${DOMAIN}`) && PathPrefix(`/jellyfin`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
      - "traefik.http.routers.jellyfin.middlewares=auth"

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    depends_on:
      - traefik
      - organizr
    restart: unless-stopped
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/bazarr:/config
      - ${ROOT}:/media
    ports:
      - 6767:6767
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`${DOMAIN}`) && PathPrefix(`/bazarr`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls.certresolver=myresolver"
      - "traefik.http.routers.bazarr.middlewares=auth"

  subfinder:
    container_name: subfinder
    image: superng6/subfinder
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TASK=2h
      - UMASK_SET=022
    volumes:
      - ${ROOT}/config/subfinder:/config
      - ${ROOT}:/media
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: unless-stopped
    ports:
      - 8082:80
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpass
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
    volumes:
      - nextcloud-www:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DOMAIN}`) && PathPrefix(`/nextcloud`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=myresolver"
      - "traefik.http.routers.nextcloud.middlewares=cloud_headers,cloud_redirectregex"
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=ALLOW-FROM https://    ${DOMAIN}"
      - "traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self'   ${DOMAIN}"
      - "traefik.http.middlewares.cloud_headers.headers.framedeny=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsPreload=true"
      - "traefik.http.middlewares.cloud_headers.headers.stsSeconds=15552001"
      - "traefik.http.middlewares.cloud_redirectregex.redirectregex.regex=/.well-known/            (card|cal)dav"
      - "traefik.http.middlewares.cloud_redirectregex.redirectregex.replacement=/remote.php/dav/"

  db:
    restart: always
    image: postgres:11
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextcloud
    volumes:
      - nextcloud-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/var/lib/redis


volumes:
  nextcloud-www:
    driver: local
  nextcloud-db:
    driver: local
  redis:
    driver: local
